### ISSUE TITLE
Pods folder missing

### ISSUE THREAD

**Issue by wellkunnected** [ramyathay/locate_your_friend#1]
Hi,

I would like to test out this app but it is missing the pods folders for the podfile and podlock file. Are you still working on this or is this something you can include with the project so that it builds correctly? Thanks for your help :)

**Comment by ramyathay** [comment]
Hey ,

So the PodFile is a really large file and difficult to upload on git . So I have included the link to create a PodFile in the README file. Please try doing the same and if you have issues do let me know!

**Comment by wellkunnected** [comment]
Thanks I'll check it out :)
